name: build flatpak
on: |
  push
  pull_request
jobs:
  flatpak-build:
    name: flatpak build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: |
          dev.neovide.neovide
          com.adobe.photoshop2021
          com.adobe.photoshop2022
          com.adobe.photoshop2023
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          dnf install -y node flatpak flatpak-builder
          echo '${{ secrets.private_gpg }}' | gpg --import
          git clone 'https://github.com/gmanka-flatpaks/${{ matrix.repos }}'
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak-builder --user --gpg-sign=gmankab@gmail.com --install-deps-from=flathub --repo=repo ./build '${{ matrix.repos }}/${{ matrix.repos }}.yml'
      - name: upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !env.ACT }}
        with:
          name: ${{ matrix.repos }}-repo
          path: repo
  deployment:
    name: deployment
    needs:
      flatpak-build
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-24.08
      options: --privileged
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: deps
        run: |
          dnf install -y node flatpak flatpak-builder
          echo '${{ secrets.private_gpg }}' | gpg --import
      - name: act download artifacts
        uses: actions/download-artifact@v4
        if: ${{ env.ACT }}
        with:
          github-token: ${{ secrets.gh_pat }}
          run-id: 12618822512
          path: artifacts
      - name: github download artifacts
        uses: actions/download-artifact@v4
        if: ${{ !env.ACT }}
        with:
          path: artifacts
      - name: write metadata
        run: |
          mkdir ./deploy/repo
          ostree init --mode=archive-z2 --repo ./deploy/repo
          for dir in ./artifacts/* ; do
            mkdir -p $dir/refs/remotes $dir/refs/mirrors
            touch $dir/refs/remotes/.gitkeep $dir/refs/mirrors/.gitkeep
            ostree --repo=./deploy/repo pull-local $dir
          done
          flatpak build-update-repo --gpg-sign=gmankab@gmail.com ./deploy/repo
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ !env.ACT }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          force_orphan: true

